[package]
name = "step"
version = "0.1.0"
edition = "2021"

[lib]
name = "step"
crate-type = ["staticlib"] # Creates static lib

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloc-cortex-m = { version = "0.4.4"}
