[package]
name = "$PEDAL_PATCH_NAME"
version = "0.1.0"
edition = "2021"

[lib]
name = "$PEDAL_PATCH_NAME"
crate-type = ["staticlib"] # Creates static lib

[dependencies]
alloc-cortex-m = { version = "0.4.4"}
cortex-m = "0.7.7"
emballoc = "0.2.0"
libc = "0.2"
